# Generated by Django 4.2.7 on 2023-12-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
    ]
