# Generated by Django 4.2.7 on 2023-12-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0003_tipos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipos',
        ),
    ]
