# Generated by Django 4.2.7 on 2023-12-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0006_nomevaigem_pagamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kminical', models.IntegerField()),
                ('kmfinal', models.IntegerField()),
                ('kmrodado', models.IntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.tipos')),
                ('idcarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.carros')),
                ('idcidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.cidades')),
                ('idpagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.pagamentos')),
                ('idviagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.nomevaigem')),
            ],
        ),
    ]
